- hosts: servers
  gather_facts: no
  tasks:
    - name: install git
      ansible.builtin.apt:
        name: git
        state: present
        update-cache: yes
      become: yes
      tags: [git, apps]

    - name: install make
      ansible.builtin.apt:
        name: make
        state: present
        update-cache: yes
      become: yes
      tags: [make, apps]

    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update-cache: yes
      become: yes
      tags: [nginx, apps]

    - name: create user arya
      ansible.builtin.user:
        name: arya
        state: present
        shell: /bin/bash
        createhome: yes
      become: yes
      tags: [arya, users]

    - name: create user sansa
      ansible.builtin.user:
        name: sansa
        state: present
        shell: /bin/bash
        createhome: yes
      become: yes
      tags: [sansa, users]

    - name: create user tirion
      ansible.builtin.user:
        name: tirion
        state: present
        shell: /bin/bash
        createhome: yes
      become: yes
      tags: [tirion, users]