- hosts: servers
  vars:
    nginx_port: 80
    root_dir: /usr/share/nginx/html
    string: This is server {{ server_name }}!
    date: "{{ansible_date_time['date']}}"
    time: "{{ansible_date_time['time']}}"
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update-cache: yes
      become: yes
      tags: [nginx, apps]

    - name: install cowsay
      ansible.builtin.apt:
        name: cowsay
        state: present
        update-cache: yes
      become: yes
      tags: [cowsay, apps]
    
    - name: cowsay command
      ansible.builtin.command: "cowsay 'This is server {{server_name}}!'"
      register: cowsay_result

    - ansible.builtin.debug: msg={{ string | upper }}

    - name: update nginx index
      ansible.builtin.template:
        src: files/index.html
        dest: "{{root_dir}}/index.html"
      notify:
        - restart nginx
      become: yes
      tags: [index, nginx]

    - name: update nginx config
      ansible.builtin.template:
        src: files/nginx.conf
        dest:  /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes
      tags: [index, nginx]
    
  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
